# Docker Compose Override File
# This file allows you to override default configurations
# Copy this file and modify as needed for your environment

version: '3.8'

services:
  frontend:
    environment:
      # Override the API base URL for your environment
      - API_BASE_URL=http://localhost:8080/data-import
      # For production, you might use:
      # - API_BASE_URL=https://your-domain.com/data-import

  app:
    environment:
      # Override Spring Boot configuration
      - SPRING_PROFILES_ACTIVE=docker
      # Add additional environment variables as needed
      # - KEYCLOAK_AUTH_PASSWORD=your_actual_password
      # - DESTINATION_API_TOKEN=your_actual_token

  mysql:
    environment:
      # Override MySQL configuration if needed
      - MYSQL_ROOT_PASSWORD=rootpassword123
      - MYSQL_PASSWORD=import_password123
    # Uncomment to persist data in a specific location
    # volumes:
    #   - /your/data/path:/var/lib/mysql