# Production Docker Compose Configuration
# Use this file for production deployments

version: '3.8'

services:
  app:
    build: .
    container_name: data-import-app-prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/data_import_db?useSSL=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - KEYCLOAK_AUTH_PASSWORD=${KEYCLOAK_PASSWORD}
      - DESTINATION_API_TOKEN=${DESTINATION_TOKEN}
      - JAVA_OPTS=-Xmx2g -Xms1g -XX:+UseG1GC -XX:+UseStringDeduplication
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - data-import-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/data-import/api/health"]
      timeout: 30s
      retries: 5
      interval: 30s
      start_period: 60s
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 2.5G
        reservations:
          memory: 1G

  frontend:
    build: 
      context: ./angular-migration-ui
      dockerfile: Dockerfile
    container_name: data-import-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8080/data-import}
    depends_on:
      - app
    networks:
      - data-import-network

  mysql:
    image: mysql:8.0.43
    container_name: data-import-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/logs:/var/log/mysql
    networks:
      - data-import-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 40s

volumes:
  mysql_prod_data:
    driver: local

networks:
  data-import-network:
    driver: bridge