# Development environment values
# Override default values for development deployment

# MySQL Configuration for Development
mysql:
  primary:
    persistence:
      size: 10Gi
    resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 512Mi
        cpu: 250m

# Backend Configuration for Development
backend:
  replicaCount: 1
  
  image:
    tag: "dev"
    pullPolicy: Always
  
  resources:
    limits:
      memory: 1Gi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 250m
  
  env:
    JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseG1GC"
    LOGGING_LEVEL_ROOT: "DEBUG"
    LOGGING_LEVEL_COM_IMPORTSERVICE: "DEBUG"
    DESTINATION_API_LOGGING_ENABLED: "true"
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: api.data-import.dev.local
        paths:
          - path: /
            pathType: Prefix

# Frontend Configuration for Development
frontend:
  replicaCount: 1
  
  image:
    tag: "dev"
    pullPolicy: Always
  
  resources:
    limits:
      memory: 128Mi
      cpu: 100m
    requests:
      memory: 64Mi
      cpu: 50m
  
  autoscaling:
    enabled: false
  
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: data-import.dev.local
        paths:
          - path: /
            pathType: Prefix

# Disable production features for development
podDisruptionBudget:
  enabled: false

monitoring:
  enabled: false