{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-import-service.mysql.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-import-service.mysql.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
{{- end }}