{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-import-service.mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-import-service.mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "data-import-service.mysql.selectorLabels" . | nindent 4 }}
{{- end }}